# numpy indexing

import numpy library to have access to numpy

In [30]:
import numpy as np

create array with ascending numbers

In [31]:
arr = np.arange(0,11)

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

select a value from array based on index

In [33]:
arr[8]

8

select a slice of array values
starting location, up to but not including

In [34]:
arr[1:5]

array([1, 2, 3, 4])

## broadcasting
numpy arrays differ from normal python arrays in that the numpy arrays
have the ability to broadcast

this kind of operation cannot be done with a normal python list
i can grab a slice of an array and set it to 100
this is known as broadcasting

In [35]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

set it back to previous value

In [36]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### copying

You will notice here that a slice of an array is not a copy of the original 
array but is a view of the original array. In truth, it is a pointer. 
If you want to copy the original
array, you must explicitly tell numpy that you want a copy. The reason why
it is this way is to avoid memory issues, such as running out of ram 
when working with large datasets.

In [37]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [38]:

slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [39]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

here, we will explicitly copy the array

In [40]:
arr_copy = arr.copy()
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [44]:
arr_copy

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

here, we will change the copy, and we will see that the original is the same

In [45]:
arr_copy[:] = 200
arr_copy

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

In [46]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

general format is mat[row][col] mat[row,col]

In [52]:
mat = np.array([[5,10,15],[20,25,30],[35,40,45]])
mat

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

grab first array

In [53]:
mat[0]

array([ 5, 10, 15])

grab last array

In [51]:
mat[2]

array([35, 40, 45])

grab individual value - there are two ways

In [54]:
mat[1][1]

25

In [55]:
mat[1,1]

25

In [56]:
mat[:2,1:]

array([[10, 15],
       [25, 30]])

## Conditional Selection

conditional selection is a very important topic to be familiar with

In [57]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

I want to grab elements off this array based on some kind of comparison operator

here, i am comparing my entire array to the number four, and i will
receive an array of booleans.

In [58]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

I can assign the result to a new array, then pass that new array into the old
array, and what is returned is an array with values only where the results 
are true.

you can also pass the operation of that array into itself, as seen with
```arr[arr>4]```

doing such things are very common with numpy and pandas

In [60]:
bool_arr = arr > 4

In [61]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [62]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])