In [1]:
import numpy as np

In [2]:
# Creating Numpy Array

In [3]:
my_list = [1,2,3]

In [8]:
# previous list can be cast as a numpy array
x = np.array(my_list)

In [10]:
type(x)

numpy.ndarray

In [11]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [12]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
list(range(0,5))

[0, 1, 2, 3, 4]

In [14]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [15]:
## starting point, end point, step size
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [16]:
# allows us to create an array or matrix of zeros
np.zeros(3)

array([0., 0., 0.])

In [19]:
# pass in a tuple to have it create a matrix
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
# helps us create an array or matrix of ones
np.ones(4)

array([1., 1., 1., 1.])

In [21]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
# linearly spaced elements
# return evenly spaced numbers over a specified interval
# takes start, stop, num
# 3 evenly spaced numbers between zero and ten:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [24]:
np.linspace(0,10,30)

array([ 0.        ,  0.34482759,  0.68965517,  1.03448276,  1.37931034,
        1.72413793,  2.06896552,  2.4137931 ,  2.75862069,  3.10344828,
        3.44827586,  3.79310345,  4.13793103,  4.48275862,  4.82758621,
        5.17241379,  5.51724138,  5.86206897,  6.20689655,  6.55172414,
        6.89655172,  7.24137931,  7.5862069 ,  7.93103448,  8.27586207,
        8.62068966,  8.96551724,  9.31034483,  9.65517241, 10.        ])

In [25]:
# identity matrix
# identity matrix is a square matrix of zeros where the diagonal is one
# created with the eye() numpy method
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
# numpy's random module
# this is one random number between 0 and 1
np.random.rand(1)

array([0.27484671])

In [27]:
# returns a 5 by 5 matrix
np.random.rand(5,5)

array([[0.1897027 , 0.09022499, 0.19241188, 0.70843443, 0.02302112],
       [0.95309634, 0.74534424, 0.71100177, 0.51462996, 0.62525169],
       [0.51088484, 0.72703779, 0.10615438, 0.3342429 , 0.23521669],
       [0.54149216, 0.93813733, 0.87547603, 0.33581038, 0.29774576],
       [0.78620178, 0.11901843, 0.92986804, 0.98014055, 0.32605757]])

In [28]:
# returns from a standard normal distribution, or bell curve
# it is centered at zero, with a variance of one
# because it is a standard normal distribution, not all numbers have the
# same chance of being picked
np.random.randn(5)

array([ 1.79278136, -1.12527258,  0.00370764, -0.57021609,  1.51240017])

In [32]:
# returns a random integer between low and high
# 1 is low and 100 is high in this case, with 10 ints being returned
np.random.randint(1,100, 10)

array([79, 47, 56, 90, 21, 89, 69, 47, 68, 81])

In [35]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [38]:
# reshapes an array to a different size
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [42]:
# shape indicates that it is 5 by 5
arr.reshape(5,5).shape

(5, 5)

In [43]:
# returns what data type array holds
arr.dtype

dtype('int32')

In [44]:
ranarr

array([ 5, 45, 39, 24,  5, 39, 38, 29,  4,  5])

In [50]:
# returns highest value from array
ranarr.max()

45

In [51]:
# returns lowest value from array
ranarr.min()

4

In [48]:
# returns index of max value
ranarr.argmax()

1

In [49]:
# returns index of min value
ranarr.argmin()

8